#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build, tag, and push
        run: |
          IMAGE_VERSION=$(cat VERSION)
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo "Building version ${IMAGE_VERSION} of image ${IMAGE_NAME}"
          docker build -t ${IMAGE_NAME} .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${IMAGE_VERSION}"
          echo "$Pushing ${IMAGE_NAME}:${IMAGE_VERSION}"
          docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}"
          echo "Pushing ${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}"
          docker push "${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}"
        env:
          IMAGE_NAME: quay.io/eclipse/che-buildkit-base
